version: "3.9"
services:
  wowhead-news-rss-filter:
    image: wowhead-news-rss-filter:latest
    build: .
    container_name: wowhead-news-rss-filter
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
networks:
  default:
    name: wowhead-news-rss-filter-network
    driver: bridge
